Start time: 2023-12-26 00:19:47.078209
Traceback (most recent call last):
  File "/mnt/nas/home/huangyixin/AI/train.py", line 377, in <module>
    training_pipeline = TrainPipeline(2e-3, init_model, device)
  File "/mnt/nas/home/huangyixin/AI/train.py", line 175, in __init__
    self.net = PolicyValueNet(board_size,
  File "/mnt/nas/home/huangyixin/AI/model.py", line 276, in __init__
    self.net = Net_Res(board_size, feature_channel, num_res).cuda()
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/nn/modules/module.py", line 689, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/huangyixin/anaconda3/envs/gomoku/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
